---
- name: Deploy an OVA
  hosts: localhost
  gather_facts: no
  vars_files:
    - /app/vars.yaml
  tasks:
  - name: Deploy OVA
    vmware_deploy_ovf:
      validate_certs: False
      hostname: 192.168.2.203
      username: root
      password: C1$c01234
      ovf: '/app/ubuntu-16.04-server-cloudimg-amd64.ova'
      wait_for_ip_address: true
      #datacenter: "{{ datacenter_name }}"
      folder: "{{ folder }}"
      #cluster: "{{ cluster_name }}"
      name: "test123"
      datastore: "datastore1"
      disk_provisioning: "thin"
      power_on: "yes"

